clear all
clc

% This script calculates the local fraction of two bipartite behaviors under
% finite detection efficiency:
%   (i)  the two-qubit behavior generated by Generate_Pbox(ep),
%   (ii) the Eberhard behavior loaded from 'Eberhard_pbox.mat'.
% For a given epsilon (ep) and detection efficiency (eta), it:
%   - generates the corresponding quantum behavior p_ep,
%   - loads the Eberhard behavior p_box,
%   - updates both behaviors by assigning all non-detected events to the
%     last outcome via Det_Box_Update,
%   - computes the local fraction of the updated behaviors using
%     LocalFraction.
% Dependencies:
%   Generate_Pbox.m, Det_Box_Update.m, LocalFraction.m, Eberhard_pbox.mat and CVX


% set the parameter for epsilon
ep = 0.98;
% generate the quantum behavior for the parameter epsilon
p_ep = Generate_Pbox(ep);

% load the Eberhard behavior
load('Eberhard_pbox.mat')  % expects variable p_box

% set the detection efficiency parameter eta
eta = 0.68;
% update the behavior by taking into account the non-clicked events
p_ep_eta       = Det_Box_Update(eta, p_ep);
p_Eberhard_eta = Det_Box_Update(eta, p_box);

% calculate the local fraction of the updated behavior
lf_ep_eta       = LocalFraction(p_ep_eta)
lf_Eberhard_eta = LocalFraction(p_Eberhard_eta)


